### ISSUE TITLE
TypeError: ceramic.setDIDProvider is not a function

### ISSUE THREAD

**Issue by Sactorum** [ceramicstudio/self.id#25]
While trying to execute de bootstrap.js, this error was happening:
"TypeError: ceramic.setDIDProvider is not a function
    at run (/home/pepe/Descargas/self.id-master/scripts/bootstrap.js:13:17)
    at Object.<anonymous> (/home/pepe/Descargas/self.id-master/scripts/bootstrap.js:32:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
"

**Comment by PaulLeCam** [comment]
Thanks for reporting this, sorry this script and the related instructions are outdated, I removed them.
